sudo: required
services:
    - docker

before_install:
    - docker build -t bmaharjan/docker-boilerplate -f Dockerfile.dev .

script:
    - docker run -e CI=true bmaharjan/docker-boilerplate npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-524741345639"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    decret_access_key:
        secure: "$AWS_SECRET_KEY"