sudo: required
services:
    - docker

before_install:
    - docker build it bmaharjan/docker-boilerplate -f Dockerfile.dev .

script:
    - docker run bmaharjan/docker-boilerplate npm run test -- --coverage